variable "aws_profile" {}
variable "aws_region" {}
variable "auditworker_iam_fleet_role" {}
variable "auditworker_spot_price" {}
variable "auditworker_allocation_strategy" {}
variable "auditworker_wait_for_fulfillment" {}
variable "auditworker_target_capacity" {}
variable "auditworker_replace_unhealthy_instances" {}
variable "auditworker_valid_until" {}
variable "auditworker_excess_capacity_termination_policy" {}
variable "auditworker_instance_type" {}
variable "auditworker_ami" {}
variable "auditworker_key_name" {}
variable "auditworker_availability_zone" {}
variable "auditworker_vpc_security_group_ids" {}
variable "auditworker_subnet_id" {}
variable "auditworker_associate_public_ip_address" {}
variable "auditworker_delete_on_termination" {}
variable "auditworker_name" {}
variable "auditworker_env" {}
variable "auditworker_instancetype" {}
